### ISSUE TITLE
netrunnerbot - replace netrunnerdb.com/find queries with the NRDB API

### ISSUE THREAD

**Issue by Venerax** [b0wmz1337/redditbots#3]
Querying netrunnerdb.com/find/?q= with the search term seems clunky to me - it is overly reliant on how netrunnerdb presents the search results, and thus quite brittle.

Instead, I suggest we parse the netrunnerdb.com/api/cards API periodically and save a local copy of the data we are interested in (card title, NRDB link, possibly image and ANCUR link). This has a couple of advantages:
- We can perform our own search over the list of names. We can thus support regex, and return multiple results for one search term (maybe we could return [[ash]] as a collapsible list containing both ASH and ashigaru)
- It will be very easy to include as much information as we want to display: the API contains every piece of data we may want.

**Comment by Venerax** [comment]
This is probably best done with some sort of APIManager class to handle polling the API, parsing the JSON and storing the data in whatever form is most convenient (a list of Card objects?). We could then replace the BeautifulSoup stuff in searchNRDB with a local search on our data. (On a second look, it appears that regex may be supported, but the remaining advantages still stand)

**Comment by b0wmz1337** [comment]
I checked the API docs when I started but I must've missed `/api/cards/` :d. That's a pretty solid idea, a list of Card objects saved locally will probably be much faster and more reliant.
